import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Badge, Card } from "@/components/ui";
import { getVpsPlan } from "@/lib/catalog";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const plan = await getVpsPlan(slug); if (!plan) return {};
  return { title: `${plan.providerName} ${plan.name} VPS Plan | Neroviax`, description: `${plan.cpu} vCPU, ${plan.ram} GB RAM, ${plan.storage} GB ${plan.storageType} for $${plan.priceMonthly}/month.`, alternates: { canonical: `/vps-plans/${plan.slug}` } };
}

export default async function VpsPlanPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const plan = await getVpsPlan(slug); if (!plan) notFound();
  const affiliateHref = plan.providerAffiliateLinkId ? `/go/${plan.providerAffiliateLinkId}?source=plan-detail&plan=${encodeURIComponent(plan.slug)}&placement=primary` : plan.sourceUrl;
  const specs = [['vCPU', plan.cpu], ['RAM', `${plan.ram} GB`], ['Storage', `${plan.storage} GB ${plan.storageType}`], ['Architecture', plan.architecture], ['Transfer', plan.transferTb === null ? 'Unmetered' : `${plan.transferTb} TB`], ['Network', plan.networkSpeedMbps ? `${plan.networkSpeedMbps} Mbps` : 'Not published'], ['IPv4', plan.ipv4 ? 'Included/available' : 'No'], ['IPv6', plan.ipv6 ? 'Yes' : 'No'], ['Backup', plan.backupAvailable ? 'Available' : 'No'], ['Snapshots', plan.snapshotAvailable ? 'Available' : 'No'], ['SLA', plan.slaPercent === null ? 'Not published' : `${plan.slaPercent}%`], ['Setup fee', `$${plan.setupFee}`]];
  return <main className="min-h-[70vh] bg-[var(--color-bg-deep)] px-5 py-14 lg:px-8"><div className="mx-auto max-w-5xl"><Link href="/vps-plans" className="text-sm text-slate-400 hover:text-white">← VPS plan database</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><div><Badge variant="azure">{plan.providerName}</Badge><h1 className="mt-4 text-4xl font-extrabold text-white sm:text-5xl">{plan.name}</h1><p className="mt-4 text-slate-400">Available in {plan.locations.map((location) => location.country).filter((value, index, values) => values.indexOf(value) === index).join(", ")}.</p><Link href={`/providers/${plan.providerSlug}`} className="mt-5 inline-block text-sm text-[var(--color-brand-light)] hover:text-white">View {plan.providerName} profile →</Link></div><Card className="p-6"><p className="text-xs uppercase tracking-wider text-slate-500">Monthly price</p><p className="mt-2 text-4xl font-extrabold text-white">${plan.priceMonthly} <span className="text-sm font-normal text-slate-500">{plan.currency}/mo</span></p><p className="mt-1 text-xs text-slate-500">Setup ${plan.setupFee}</p><a href={affiliateHref} target="_blank" rel={plan.providerAffiliateLinkId ? "sponsored noopener noreferrer" : "noopener noreferrer"} className="mt-6 inline-flex w-full justify-center rounded-xl bg-[var(--color-brand)] px-4 py-3 text-sm font-bold text-white">View plan →</a><p className="mt-4 text-center text-xs text-slate-500">Updated {plan.lastUpdated}</p></Card></div>
    <div className="mt-8"><Link href={`/compare?plans=${plan.slug}`} className="inline-flex rounded-xl border border-[var(--color-border-strong)] bg-[var(--color-action)] px-4 py-3 text-sm font-bold text-white hover:bg-[var(--color-action-hover)]">Add to comparison →</Link></div>
    <section className="mt-12"><h2 className="text-2xl font-extrabold text-white">Plan specifications</h2><dl className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{specs.map(([label, value]) => <Card key={String(label)} className="p-5"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-2 font-bold text-white">{value}</dd></Card>)}</dl></section>
    <section className="mt-12 grid gap-6 md:grid-cols-2"><Card className="p-6"><h2 className="font-bold text-white">Network and regions</h2><ul className="mt-4 space-y-2 text-sm text-slate-400">{plan.locations.map((location) => <li key={location.id}>{location.name}, {location.country} · {location.region}</li>)}</ul>{plan.egressCostPerGb !== null && <p className="mt-4 text-xs text-slate-500">Published extra egress: ${plan.egressCostPerGb}/GB</p>}</Card><Card className="p-6"><h2 className="font-bold text-white">Catalog notes</h2><p className="mt-4 text-sm leading-relaxed text-slate-400">{plan.note || "No additional notes."}</p>{plan.promotion && <p className="mt-4 rounded-xl bg-[var(--color-success-soft)] p-3 text-sm text-[var(--color-success-text)]">{plan.promotion}</p>}<a href={plan.sourceUrl} target="_blank" rel="noopener noreferrer" className="mt-5 inline-block text-xs text-slate-400 underline">Verify official pricing source ↗</a></Card></section>
  </div></main>;
}
